version: 2
jobs:
  build:
    working_directory: ~/cursor
    docker:
      - image: python:3.9.0-buster
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip3 install --upgrade pip
            pip3 install -r requirements.txt
            pip3 install -e .
      - run:
          name: Install xvfb
          command: |
            apt-get update
            apt-get install -y xvfb
          background: false
      - run:
          name: Running X virtual framebuffer
          command: Xvfb -ac :99 -screen 0 1920x1080x16 +extension RANDR > /dev/null 2>&1
          background: true
      - run:
          name: Run Flake8
          command: |
            mkdir cursor/tests/artifacts
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --ignore=E402,W503,E203,E303,E722 --statistics --output-file cursor/tests/artifacts/flake8_report.txt
      - run:
          name: Run tests
          command: |
            export DISPLAY=:99
            py.test --cov . --cov-report html
            mv htmlcov cursor/tests/artifacts/
      - store_artifacts:
          path: cursor/tests/artifacts
workflows:
  version: 2
  workflow:
    jobs:
    - build
