version: 2
jobs:
  build:
    working_directory: ~/cursor
    docker:
      - image: python:3.11
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt update
            apt install -y python3-pyqt5 libcairo2-dev pkg-config python3-dev python3-tk
      - run:
          name: Install dependencies
          command: |
            pip3 install --upgrade pip
            pip3 install -e .
      - run:
          name: Install xvfb
          command: |
            apt update
            apt install -y xvfb
          background: false
      - run:
          name: Running X virtual framebuffer
          command: Xvfb -ac :99 -screen 0 1920x1080x16 +extension RANDR > /dev/null 2>&1
          background: true
      - run:
          name: Run Ruff
          command: |
            mkdir -p cursor/tests/artifacts
            pip3 install ruff
            ruff check cursor --output-format=text > cursor/tests/artifacts/ruff_report.txt || true
            ruff format --check .
      - run:
          name: Run tests
          command: |
            export DISPLAY=:99
            py.test --cov . --cov-report html
            mv htmlcov cursor/tests/artifacts/
      - store_artifacts:
          path: cursor/tests/artifacts
workflows:
  version: 2
  workflow:
    jobs:
      - build
